// <auto-generated />
namespace MyAbpZeroProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Upgrade_Abp_And_Module_Zero_To_0_7_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Upgrade_Abp_And_Module_Zero_To_0_7_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201510141938232_Upgrade_Abp_And_Module_Zero_To_0_7_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
