// <auto-generated />
namespace ModuleZeroSampleProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Abp_Upgrade_0_5_12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Abp_Upgrade_0_5_12));
        
        string IMigrationMetadata.Id
        {
            get { return "201504161031267_Abp_Upgrade_0_5_12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
