// <auto-generated />
namespace ModuleZeroSampleProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ModuleZero_Upgrade_Pre_5_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModuleZero_Upgrade_Pre_5_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201501272022518_ModuleZero_Upgrade_Pre_5_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
